database: sandbox_data_science

# bnso_retail_score: sandbox_data_science.churn_bnso_retail_score_current_date
curr_date: CURRENT_DATE
# bnso_lease_score : sandbox_data_science.churn_bnso_lease_score_current_date

# ppo_and_churn_scores_current_date : sandbox_data_science.dummy_churn_bnsoR_bnsoL_single_score_FINAL
ppo_enr_nonenr_historical_score : sandbox_data_science.mathco_ppo_enr_nonenr_scores_historical
ppo_enr_nonenr_current_date_score : sandbox_data_science.mathco_ppo_enr_nonenr_scores_current_date
output_table_with_ppo_churn_scores : sandbox_data_science.mathco_churn_buso_ppo_current_score_table
# dummy_delete : sandbox_data_science.dummy_delete_mathco_churn_ppo_current_score_table
historic_churn_model_scores : sandbox_data_science.churn_model_buso_score_hist
historic_churn_mapped_ppo_scores : sandbox_data_science.mathco_churn_buso_ppo_historic_score_table
churn_scores_single_table : sandbox_data_science.churn_buso_retail_score_current_date
ownership : ${unification_db}.enriched_cms_consmvhclownshp